# -*- coding: utf-8 -*-
"""Sentimental_emotion_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3bGcyiO9UKDWuab1b0R7BtXI7hGtbl_
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


#library help to load datasets
from datasets import load_dataset

emotion_dataset =load_dataset('dair-ai/emotion')
train_text =  emotion_dataset['train']['text']
train_label = emotion_dataset['train']['label']
test_text =  emotion_dataset['test']['text']
test_label = emotion_dataset['test']['label']

label_names = emotion_dataset['train'].features['label'].names

df_train = pd.DataFrame(
    {
        'text':train_text,
        'label':[label_names[i] for i in train_label]
    }
)

df_test = pd.DataFrame(
    {
        'text':test_text,
        'label':[label_names[i] for i in test_label ]
    }
)

df_train.isnull().sum()

"""## 3. Exploratory Data Analysis"""

sns.countplot(x='label', data = df_train, order=df_train['label'].value_counts().index)

"""# Data Preprocessing using NLP

First of all we will do tokenization
"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_words = 10000

tokenizer = Tokenizer(num_words=max_words, oov_token='<unk>')
tokenizer.fit_on_texts(df_train['text'])

train_sequence = tokenizer.texts_to_sequences(df_train['text'])
test_sequence = tokenizer.texts_to_sequences(df_test['text'])

"""Now we will applying padding for the all the Input have similar size"""

padded_train_sequence = pad_sequences(train_sequence, maxlen=50, padding='post', truncating ='post')
padded_test_sequence = pad_sequences(test_sequence, maxlen=50, padding='post', truncating ='post')

train_labels = np.array(train_label)
test_labels = np.array(test_label)

num_classes = len(np.unique(train_labels))
num_classes

print(f"Vocabulary size: {max_words}")
print(f"Number of classes: {num_classes}")
print(f"Max sentence length :{ padded_train_sequence.shape[1]}")

"""## Shared Training Utilites"""

from sklearn.utils import class_weight

class_weights = class_weight.compute_class_weight(
    class_weight ='balanced',
    classes=np.unique(train_labels),
    y = train_labels

)
class_weight_dict = dict(enumerate(class_weights))

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights = True
)



"""## Plain Modules we will create The Simple RNN, Standard LSTM, Standard GRU models"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, LSTM, GRU, Dropout


rnn_model = Sequential(
    [
        Embedding(input_dim = max_words,
        output_dim = 128,
        input_length = 50,),
        SimpleRNN(units=128, return_sequences=True),
        Dropout(0.5),
         SimpleRNN(units=64),
         Dropout(0.5),
        Dense(units=num_classes, activation='softmax') #output layer
    ]
)

rnn_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy']  )
rnn_model.fit(
    padded_train_sequence,
    train_labels,
    validation_data=(padded_test_sequence, test_labels),
    epochs = 20,
    batch_size = 32,
    class_weight = class_weight_dict,
    callbacks = [early_stopping]
)

rnn_loss, rnn_accuracy = rnn_model.evaluate(padded_test_sequence, test_labels)
print(f"RNN Loss: {rnn_loss}")
print(f"RNN Accuracy: {rnn_accuracy}")

"""## LSTM Model"""

lstm_model = Sequential(
    [
        Embedding(input_dim = max_words,
        output_dim = 128,
        input_length = 50,),
        LSTM(units=128, return_sequences=True),
        Dropout(0.5),
         LSTM(units=64),
         Dropout(0.5),
        Dense(units=num_classes, activation='softmax') #output layer
    ]
)

lstm_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy']  )
lstm_model.fit(
    padded_train_sequence,
    train_labels,
    validation_data=(padded_test_sequence, test_labels),
    epochs = 20,
    batch_size = 32,
    class_weight = class_weight_dict,
    callbacks = [early_stopping]
)

lstm_loss, lstm_accuracy = lstm_model.evaluate(padded_test_sequence, test_labels)
print(f"RNN Loss: {lstm_loss}")
print(f"RNN Accuracy: {lstm_accuracy}")

"""## GRU Model"""

gru_model = Sequential(
    [
        Embedding(input_dim = max_words,
        output_dim = 128,
        input_length = 50,),
        GRU(units=128, return_sequences=True),
        Dropout(0.5),
        GRU(units=64),
         Dropout(0.5),
        Dense(units=num_classes, activation='softmax') #output layer
    ]
)

gru_model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy']  )
gru_model.fit(
    padded_train_sequence,
    train_labels,
    validation_data=(padded_test_sequence, test_labels),
    epochs = 20,
    batch_size = 32,
    class_weight = class_weight_dict,
    callbacks = [early_stopping]
)

gru_loss, gru_accuracy = rnn_model.evaluate(padded_test_sequence, test_labels)
print(f"GRU Loss: {gru_loss}")
print(f"GRU Accuracy: {gru_accuracy}")

result_df = pd.DataFrame(
    {
        'Model':['RNN', 'LSTM', 'GRU'],
        'Test Loss':[rnn_loss, lstm_loss, gru_loss],
        ' Test Accuracy':[rnn_accuracy, lstm_accuracy, gru_accuracy]
    }
).sort_values(by=' Test Accuracy', ascending=False)

result_df

"""## Bidirectional GRU"""

from tensorflow.keras.layers import Bidirectional
BiGRU = Sequential(
    [
         Embedding(input_dim = max_words,
        output_dim = 300,
        input_length = 50,),
       Bidirectional(GRU(128)),
     Dropout(0.5),
      Dense(num_classes, activation='softmax') #output layer

    ]


)

BiGRU.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy']  )

BiGRU.summary()

BiGRU.fit(
    padded_train_sequence,
    train_labels,
    validation_data=(padded_test_sequence, test_labels),
    epochs = 20,
    batch_size = 32,
    class_weight = class_weight_dict,
    callbacks = [early_stopping]
)

BiGRU_loss, BiGRU_accuracy = BiGRU.evaluate(padded_test_sequence, test_labels)
print(f"BiGRU Loss: {BiGRU_loss}")
print(f"BiGRU Accuracy: {BiGRU_accuracy}")

from tensorflow.keras.layers import Bidirectional

BiLSTM = Sequential(
    [
         Embedding(input_dim = max_words,
        output_dim = 300,
        input_length = 50,),
       Bidirectional(LSTM(128)),
     Dropout(0.5),
      Dense(num_classes, activation='softmax') #output layer

    ]


)

BiLSTM.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics =['accuracy']  )

BiLSTM.fit(
    padded_train_sequence,
    train_labels,
    validation_data=(padded_test_sequence, test_labels),
    epochs = 20,
    batch_size = 32,
    class_weight = class_weight_dict,
    callbacks = [early_stopping]
)

BiLSTM_loss, BiLSTM_accuracy = BiLSTM.evaluate(padded_test_sequence, test_labels)
print(f"BiLSTM Loss: {BiLSTM_loss}")
print(f"BiLSTM Accuracy: {BiLSTM_accuracy}")

"""## Final Model Confusion Matrix"""

from sklearn.metrics import confusion_matrix

BiGRU_prediction = np.argmax(BiGRU.predict(padded_test_sequence), axis=1)


sns.heatmap(confusion_matrix(test_label, BiGRU_prediction), annot=True, fmt='d', cmap='Blues', xticklabels=label_names, yticklabels=label_names)
plt.xlabel('Predicted')
plt.ylabel('True')

"""## Final Prediction"""

sample_texts = [
    "I can't believe how happy I am right now, this is amazing!",
    "I feel so alone and hopeless today.",
    "I am furious that they cancelled the trip at the last minute.",
    "I feel terrified when walking down dark alleyways alone.",
    "I was shocked and completely surprised by the unexpected gift!"
]



sample_sequences = tokenizer.texts_to_sequences(sample_texts)
sample_padded_sequences = pad_sequences(sample_sequences, maxlen=50, padding='post', truncating='post' )

sample_predictions = np.argmax(BiGRU.predict(sample_padded_sequences), axis=1)

sample_predictions

for i in range(len(sample_texts)):
 print(f'Text: {sample_texts[i]}\nPredicted Emotion: {label_names[sample_predictions[i]]}')

import os
import pickle


model_dir = 'Artifacts'
os.makedirs(model_dir, exist_ok=True) #this is the folder where our exported file will be their

#Save our BiGRU Model
BiGRU.save(os.path.join(model_dir, 'BiGRU_Model.keras'))

#save the tokinzer model
with open(os.path.join(model_dir, 'tokenizer.pkl'), 'wb') as file:
    pickle.dump(tokenizer, file)

